sudo: false

language: "perl"
before_install:
    - git submodule update --init --recursive
    - yes | cpanm --notest --verbose Module::Install Module::Install::AuthorTests Module::Install::ReadmeFromPod Module::Install::Repository Module::Install::XSUtil XSLoader


